export const materials = [
  "Rigid Denim",
  "Vintage Denim",
  "Lightweight Denim",
  "Fleece",
  "Signature Denim",
  "Linen Blend",
  "Cotton",
  "Synthetic",
  "YPB motionTEK",
  "Cotton Nylon",
  "Cotton Tencel",
  "YPB neoKNIT MAX",
  "Denim",
  "YPB neoKNIT",
  "Cotton Linen",
  "Cotton Blend",
  "Faux Wool",
  "Canvas",
  "YPB powerSOFT",
  "Linen",
  "Vegan Leather",
  "Nylon",
  "Wool Blend",
  "Oxford",
  "Polyester Blend",
  "Vegan Suede",
  "YPB restore",
  "Polyester",
  "Sherpa",
];
